- name: Install common utilities
  become: true
  ansible.builtin.apt:
    name:
      - curl
      - wget
      - git
      - vim
      - htop
      - unzip
      - ca-certificates
      - gnupg
      - software-properties-common
      - net-tools
      - jq
      - ufw
      - fail2ban
    state: present
