- name: Install nginx
  become: true
  ansible.builtin.apt:
    name: nginx
    state: present
- name: Enable nginx service
  become: true
  service:
    name: nginx
    enabled: yes
- name: Start nginx service
  become: true
  service:
    name: nginx
    state: started
