Vagrant.configure("2") do |config|
  config.vm.box_check_update = false

  config.vm.define "cluster" do |cluster|
    cluster.vm.hostname = "cluster"
    cluster.vm.box = "ubuntu/focal64"
    cluster.vm.network :private_network, ip: "10.0.0.102"
  end
  config.ssh
  config.vm.synced_folder '.', '/vagrant', disabled: true

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "2048"
     vb.cpus = 2
  end
  config.vm.provision "shell", inline: <<-SHELL
     set -e  # Exit on any error
     
     echo "Starting provisioning..."
     apt-get update
     apt-get install -y docker.io curl wget
     
     # Add vagrant user to docker group
     usermod -aG docker vagrant
     sudo ufw disable
     echo "Installing k3s..."
     curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable=helm-controller" sh
     
     # Wait for k3s to be ready
     sleep 30
     
     echo "Setting up kubectl..."
     curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
     sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
     alias k="kubectl"
     # Setup kubectl config for vagrant user
     mkdir -p /home/vagrant/.kube
     cp /etc/rancher/k3s/k3s.yaml /home/vagrant/.kube/config
     chown -R vagrant:vagrant /home/vagrant/.kube
     chmod 600 /home/vagrant/.kube/config
    
     echo "Installing k9s..."
     wget -q https://github.com/derailed/k9s/releases/latest/download/k9s_linux_amd64.deb
     apt install -y ./k9s_linux_amd64.deb
     
     echo "Installing Flux CLI..."
     curl -s https://fluxcd.io/install.sh | sudo bash
     
     echo "Installing git and cloning repository..."
     apt install -y git
     export GITHUB_TOKEN="${GITHUB_TOKEN}"
     flux bootstrap github \
        --owner=diogoguedes11 \
        --repository=homelab \
        --branch=main \
        --path=./clusters/data \
        --personal=true
     SHELL
end

 