---
- hosts: localhost
  tasks:
    - name: Install helm if not exists
      unarchive:
        src: https://get.helm.sh/helm-v3.11.0-linux-amd64.tar.gz
        dest: /usr/local/bin
        extra_opts: "--strip-components=1"
        owner: root
        group: root
        mode: 0755
        remote_src: true
      args:
        creates: /usr/local/bin/helm
    - name: Install kube prometheus stack chart
      kubernetes.core.helm:
        atomic: true
        name: prometheus
        chart_ref: prometheus-community/kube-prometheus-stack
        chart_version: 50.3.1
        update_repo_cache: true
        create_namespace: true
        release_namespace: monitoring
        values: "{{ lookup('file', 'files/values-prometheus-stack.yaml') | from_yaml }}"
