apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-configmap
  namespace: n8n
  labels:
    app: n8n
    component: configmap
data:
  NODE_ENV: "development"
  GENERIC_TIMEZONE: "Europe/Lisbon"
  # Database configurations
  # Turn on basic auth
  N8N_BASIC_AUTH_ACTIVE: "true"
  N8N_BASIC_AUTH_USER: "n8n"
  N8N_BASIC_AUTH_PASSWORD: "n8n"
  DB_TYPE: postgres
  DB_POSTGRESDB_HOST: postgres
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: n8n
  DB_POSTGRESDB_USER: n8n
  DB_POSTGRESDB_PASSWORD: n8npass
  N8N_HOST: 0.0.0.0
  N8N_PORT: "5678"
  WEBHOOK_TUNNEL_URL: "http://172.18.0.2:30080"
  N8N_SECURE_COOKIE: "false"