Vagrant.configure("2") do |config|
    # Define the base box
    config.vm.box = "ubuntu/jammy64"
    
    # prometheus VM
    config.vm.define "prometheus" do |prometheus|
        prometheus.vm.hostname = "prometheus"
        prometheus.vm.network "public_network", bridge: "Intel(R) Ethernet Connection", adapter: 2
        prometheus.vm.provider "virtualbox" do |vb|
            vb.memory = "3072"
            vb.cpus = 2
        end
        prometheus.vm.provision "shell", inline: "sudo apt-get update && sudo apt-get upgrade -y"
        prometheus.vm.network "forwarded_port", guest: 9090, host: 1234
    end
    
    # Node VM
    config.vm.define "node1" do |node|
        node.vm.hostname = "node1"
        node.vm.network "public_network" , bridge: "Intel(R) Ethernet Connection", adapter: 2
        node.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = 1
        end
        node.vm.provision "shell", inline: "sudo apt-get update && sudo apt-get upgrade -y"
    end
end