{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: default
data:
    {{- range $key, $val := .Values.configMap.data }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
{{- end }}