networks:
  prometheus:
    driver: bridge
    name: prometheus
services:
  prometheus:
    image: prom/prometheus:latest
    container_name:
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - prometheus
    restart: always
  python-application:
    build:
      context: ./python-application
      dockerfile: Dockerfile
    container_name: python-application
    ports:
      - "81:5000"
    networks:
      - prometheus
    restart: always
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana.yml:/etc/grafana/provisioning/datasources/datasources.yml
    networks:
      - prometheus
    restart: always
