apiVersion: v1
kind: Pod
metadata:
  name: non-root-user-container
  namespace: k29
spec:
  containers:
    - image: bitnami/nginx:1.21.6
      name: secured-container
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: v1
kind: Pod
metadata:
  name: privileged-container
  namespace: k29
spec:
  containers:
    - image: bitnami/nginx:1.21.6
      name: secured-container
      securityContext:
        runAsNonRoot: true
        privileged: true
        allowPrivilegeEscalation: true
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: v1
kind: Pod
metadata:
  name: root-user-container
  namespace: k29
spec:
  containers:
    - image: nginx:1.18.0
      name: secured-container
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
