- hosts: ubuntu-vm
  pre_tasks:
    - name: update apt
      become: true
      apt:
        update_cache: true
        state: present
  tasks:
    - import_tasks: k3s/k3s.yaml
    - import_tasks: kube-prom-stack/kube-prom-stack.yml
