---
- name: install k3s cluster
  hosts: all
  become: true
  tasks:
    - name: install k3s
      shell: |
        curl -sfL https://get.k3s.io | sh -
      when: ansible_facts['os_release'] == "Ubuntu"
    - name: Install FluxCD
      shell: |
        curl -s https://fluxcd.io/install.sh | sudo bash
      when: ansible_facts['os_release'] == "Ubuntu"
- name: create kubernetes namespace
  hosts: all
  become: true
  tasks:
    - name: create namespace
      kubernetes.core.k8s:
        name: observability
        api_version: v1
        kind: Namespace
        state: present
