- hosts: ubuntu-vm
  pre_tasks:
    - name: update apt
      become: true
      apt:
        update_cache: true
        state: present
  tasks:
    # - import_tasks: baseutils/utils.yaml
    # - import_tasks: fail2ban/fail2ban.yaml
    - import_tasks: nginx/nginx.yaml
  # - include: k3s/k3s.yaml
